theme: jekyll-theme-cayman
title: 職務経歴書
description: 森田雅大の職務経歴書
show_downloads: false
google_analytics: # Google Analytics ID (optional)

# Additional settings
markdown: kramdown
highlighter: rouge
plugins:
  - jekyll-sitemap
  - jekyll-feed

# Social media settings (optional)
github:
  is_project_page: true
  is_user_page: false