name: Lint

on:
  pull_request:
    branches: [ main ]
  push:
    branches: [ main ]

jobs:
  textlint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'
      
      - name: Install dependencies
        run: |
          npm install --save-dev textlint
          npm install --save-dev textlint-rule-preset-ja-technical-writing
          npm install --save-dev textlint-rule-preset-ja-spacing
          npm install --save-dev textlint-rule-spellcheck-tech-word
      
      - name: Run textlint
        run: npx textlint docs/README.md

  markdownlint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'
      
      - name: Install markdownlint-cli
        run: npm install --save-dev markdownlint-cli
      
      - name: Run markdownlint
        run: npx markdownlint docs/README.md